name: Build zoo-node docker image

on:
  push:
    branches:
      - 'main'
      - 'devops'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-deploy:
    uses: dcSpark/zoo-node/.github/workflows/build-workflow.yml@devops
    with:
      REGISTRY: dcspark
      REPOSITORY: zoo-node
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      