FROM rust:1.75.0-slim-bookworm AS base-builder
RUN apt-get update && apt-get install pkg-config clang cmake libssl-dev --no-install-recommends -y
#
FROM base-builder AS zoo_node-builder
WORKDIR zoo
COPY . .
RUN cargo build --release --bin zoo_node
#
FROM debian:bookworm-slim AS base-release
RUN apt-get update && apt-get -y upgrade && apt-get -y --no-install-recommends install ca-certificates libssl3 && apt-get -y clean
#
FROM base-release AS zoo_node
ARG APP=/app
WORKDIR ${APP}
COPY --from=zoo_node-builder /zoo/target/release/zoo_node ${APP}
CMD ["./zoo_node"]