FROM rust:1.75.0-slim-bookworm AS base-builder
RUN apt-get update && apt-get install pkg-config clang cmake libssl-dev --no-install-recommends -y
#
FROM base-builder AS hanzo_node-builder
WORKDIR hanzo
COPY . .
RUN cargo build --release --bin hanzo_node
#
FROM debian:bookworm-slim AS base-release
RUN apt-get update && apt-get -y upgrade && apt-get -y --no-install-recommends install ca-certificates libssl3 && apt-get -y clean
#
FROM base-release AS hanzo_node
ARG APP=/app
WORKDIR ${APP}
COPY --from=hanzo_node-builder /hanzo/target/release/hanzo_node ${APP}
CMD ["./hanzo_node"]
